version: '3.3'
services:
  nextjs:
    build: .
    container_name: sixthstar_js
    ports:
      - "8081:4200"  # Exposing Next.js app on port 8080
    environment:
      NODE_ENV: production  # Run in production mode
    volumes:
      - .:/usr/src/app  # Mount the current directory into the container
    command: npm run start  # Use the start command to launch the Next.js app

  db:
    image: mysql:5.7  # MySQL image, adjust if using another DB
    container_name: sixthstar_db
    environment:
      MYSQL_ROOT_PASSWORD: Sixth*54321  # Set MySQL root password
      MYSQL_DATABASE: Sixth*54321  # Optional, specify a default DB
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    volumes:
      - db_data:/var/lib/mysql  # Persist data between container restarts

volumes:
  db_data:  # Define a volume for MySQL data persistence
